# Simple workflow for deploying static content to GitHub Pages
name: Build TOC and deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  DIRECTORY_LISTING: |
    ls ${{ github.workspace }}

jobs:
  toc-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in the repository
        id: dir_list
        run: |
          {
            echo 'DIR_LIST<<EOF'
            ls ${{ github.workspace }}
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: index.html
          write-mode: overwrite 
          contents: |
            <!-- This file is being auto-generated by Github action "buildTocAndDeployStatic.yml" $github.sha -->

            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <link rel="stylesheet" href="styles.css">
                <title>Nik's crafty samples - table of contents</title>
            </head>
            <body>
                <main>
                <h1>Table of Contents</h1>
                <p><h4>DIR_LIST</h4>$DIR_LIST</p>
                <p><h4>steps.dir_list</h4>${{steps.dir_list}}</p>
                <p><h4>steps.dir_list.outputs</h4>${{steps.dir_list.outputs}}</p>
                <p><h4>steps.dir_list.outputs.*</h4>${{steps.dir_list.outputs.*}}</p>
                </main>
            </body>
            </html>     
            
      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
